### ISSUE TITLE
Allow None select choice also

### ISSUE THREAD

**Issue by klihelp** [marktimemedia/acf-term-and-taxonomy-chooser#1]
~

**Comment by klihelp** [comment]
@marktimemedia  Can you comment please, on why you closed the issue, or do you need more info..

**Comment by marktimemedia** [comment]
More info would be nice, just writing a short sentence doesn't really tell me anything.

**Comment by klihelp** [comment]
That's nice, thanks for asking, close accepted.
@mcaskill do you have any comment?
