### ISSUE TITLE
error:

### ISSUE THREAD

**Issue by alexeightsix** [marktimemedia/acf-term-and-taxonomy-chooser#2]
Fatal error: Uncaught Error: Call to undefined function acfatspost_types_array() in /srv/www/default/wp-content/plugins/acf-advanced-taxonomy-selector/acf-advanced_taxonomy_selector-v4.php:143 Stack trace: #0 /srv/www/default/wp-includes/plugin.php(524): acf_field_advanced_taxonomy_selector->create_options(Array) #1 /srv/www/default/wp-content/plugins/advanced-custom-fields/core/fields/_functions.php(589): do_action('acf/create_fiel...', Array) #2 /srv/www/default/wp-includes/plugin.php(524): acf_field_functions->create_field_options(Array) #3 /srv/www/default/wp-content/plugins/acf-repeater/views/options.php(207): do_action('acf/create_fiel...', Array) #4 /srv/www/default/wp-content/plugins/acf-repeater/repeater.php(184): include('/srv/www/defaul...') #5 /srv/www/default/wp-includes/plugin.php(524): acf_field_repeater->create_options(Array) #6 /srv/www/default/wp-content/plugins/advanced-custom-fields/core/fields/_functions.php(589): do_action('acf/create_fiel...', Array) #7 /srv/www/default/wp-includes/plugin.php(524): in /srv/www/default/wp-content/plugins/acf-advanced-taxonomy-selector/acf-advanced_taxonomy_selector-v4.php on line 143

**Comment by alexeightsix** [comment]
im using acf v4

**Comment by marktimemedia** [comment]
Ah ok, I believe I have only tested this on v5 as I stated in my description :)

**Comment by alexeightsix** [comment]
do you suggest I upgrade to v5 or will the issue be fixed in v4?

**Comment by marktimemedia** [comment]
Since I don't use v4, and it is written differently, I'm not planning on supporting v4. Good luck!
